-- Verify Data load
USE DATABASE BRAZE_ENGAGEMENT;
USE SCHEMA EMAIL_DATA;
-- view changelog table data
SELECT * FROM BRAZE_ENGAGEMENT.EMAIL_DATA.CAMPAIGN_CHANGELOGS LIMIT 10;

-- view email sends data
SELECT * FROM BRAZE_ENGAGEMENT.EMAIL_DATA.EMAIL_SENDS LIMIT 10;

-- view email open data
SELECT * FROM BRAZE_ENGAGEMENT.EMAIL_DATA.EMAIL_OPENS LIMIT 10;

-- view email click data
SELECT * FROM BRAZE_ENGAGEMENT.EMAIL_DATA.EMAIL_CLICKS LIMIT 10;

-- view email unsubscribes data
SELECT * FROM BRAZE_ENGAGEMENT.EMAIL_DATA.EMAIL_UNSUBSCRIBES LIMIT 10;

-- view product reviews data
SELECT * FROM BRAZE_ENGAGEMENT.EMAIL_DATA.PRODUCT_REVIEWS LIMIT 10;

-------------------
Select count(*) from CAMPAIGN_CHANGELOGS;
Select count(*) from EMAIL_OPENS;
Select count(*) from EMAIL_CLICKS;
Select count(*) from EMAIL_UNSUBSCRIBES;
Select count(*) from PRODUCT_REVIEWS;
Select count(*) from BRAZE_ENGAGEMENT.EMAIL_DATA.EMAIL_SENDS;


