USE DATABASE BRAZE_ENGAGEMENT;
USE SCHEMA EMAIL_DATA;

CREATE OR REPLACE CORTEX SEARCH SERVICE PRODUCT_REVIEWS_SEARCH
  ON REVIEW_TEXT
  ATTRIBUTES RATING, PRODUCT_SENTIMENT, PURCHASE_LOCATION, PRODUCT_CATEGORY, ITEM_NAME
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 hour'
  AS (
    SELECT
        REVIEW_ID,
        USER_ID,
        RATING,
        REVIEW_TEXT,
        PRODUCT_SENTIMENT,
        REVIEW_DATE,
        PURCHASE_LOCATION,
        PRODUCT_CATEGORY,
        ITEM_NAME
    FROM BRAZE_ENGAGEMENT.EMAIL_DATA.PRODUCT_REVIEWS
  );

-- Verify the search service was created
SHOW CORTEX SEARCH SERVICES IN SCHEMA BRAZE_ENGAGEMENT.EMAIL_DATA;
